home_app/urls.py
"""
    home_app URL Configuration

"""
from django.urls import path

from home_app import views as hav


app_name = 'home_app'
urlpatterns = [
    path('', hav.index, name='index'),
    path('index/', hav.index, name='index'),
    path('mentions/', hav.mentions, name='mentions'),
    path('test_error',hav.test_error, name='test_error'),
    path('set_language/', hav.set_language, name='set_language'),
]

products_app/urls.py
"""
    home_app URL Configuration

"""
from django.urls import path

from products_app import views as pav
from home_app import views as hav


app_name = 'products_app'
urlpatterns = [
    path('', hav.index, name='index'),
    path('search', pav.search_view, name='search'),
    path('search_substitute', pav.search_substitute_view, name='search_substitute'),
    path('detail', pav.ProductDetailView.as_view(), name='detail'),
    path('save_remove_bookmark/', pav.save_remove_bookmark, name='save_remove_bookmark'),
    path('list_bookmarks/', pav.BookmarkListView.as_view(), name='list_bookmarks'),
    path('initdb', pav.InitDBView.as_view(), name='initdb'),
]

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

from home_app import views as hav


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home_app/', include('home_app.urls')),
    path('user_app/', include('user_app.urls')),
    path('products_app/', include('products_app.urls')),
    path('', hav.index, name='index'),
    path('autocomplete_search/', hav.autocomplete_search, name='autocomplete_search'),
    path('accounts/login/', RedirectView.as_view(url='/user_app/login')),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_password_complete.html'),
         name='password_reset_complete'),

]

handler400 = 'home_app.errors.handler400'
handler403 = 'home_app.errors.handler403'
handler404 = 'home_app.errors.handler404'
handler500 = 'home_app.errors.handler500'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

user_app/urls.py
"""
    home_app URL Configuration

"""
from django.urls import path
from django.contrib.auth import views as auth_views


from user_app import views as uav
from home_app import views as hav


app_name = 'user_app'
urlpatterns = [
    path('', hav.index, name='index'),
    path('user_create', uav.user_create, name='user_create'),
    path('login', uav.user_login, name='login'),
    path('user_logout', uav.user_logout, name='ulogout'),
    path('change_password', uav.change_password, name='change_password'),
    # Reset password
    path('reset_password', uav.reset_psw, name='reset_password'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="registration/reset_password_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_password_complete.html'),
         name='password_reset_complete'),
]

templates/layouts/partials/_back.html
{# the back button #}
{% load dis_play %}
<hr />
        <div class="row align-items-center justify-content-center text-center col-12">
            <input type="button" class="btn btn-primary" value="{% dis_play 'purbeurre-back-button1' %}" onClick="window.history.back();return false;" />
        </div>

templates/layouts/partials/_footer.html
{# The footer part of the templates #}
{% load dis_play %}
{% block footer %}
    <footer class="bg-light py-5">
        <div class="container">
            <div class="row col-12 small text-center text-muted">
                <div class="col-md-6 col-12">
                    <a href="{% url 'home_app:mentions' %}">{% dis_play "purbeurre-footer-text1" %}</a>
                </div>
                <div class="col-md-6 col-12">
                    <a href="{% url 'home_app:index' %}#contact">{% dis_play "purbeurre-footer-text2" %}</a>
                </div>
            </div>
        </div>
    </footer>
{% endblock footer %}

templates/layouts/partials/_nav.html
{% comment %}
    The navbar (responsive)
        contains also a searchform
        carrot and exit icons are displayed only if the user is connected
{% endcomment %}
{% load static %}
{% load dis_play %}
{% block navbar %}

    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container">
            <div id="logo" class="d-none d-sm-block">
                <a href="{% url 'index' %}"><img src="{% static 'img/logo_pur_beurre2.png' %}" alt="Pur Beurre"></a>
                <p class="text">{%  dis_play "purbeurre-nav-text1" %}</p>
            </div>
            <h2><a class="js-scroll-trigger" href="{% url 'index' %}">Pur Beurre</a></h2>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto my-2 my-lg-0">
                    <form class="form-inline my-2 my-lg-0" id="searchform_nav" method="POST" action="{% url 'products_app:search' %}">
                        {% csrf_token %}
                        <input class="form-control mr-sm-2" minlength="5" maxlength="50" name="search_menu"
                               id="search_menu" type="search" placeholder="Search - min 5 chars" aria-label="search_menu">
                    </form>
                    {% if user.is_authenticated %}
                    <div id="carrot">
                        <li class="nav-item carrot"><a href="{% url 'products_app:list_bookmarks' %}">
                            <i class="fas fa-carrot fa-2x"></i></a>
                        </li>
                        <span class="text">{%  dis_play "purbeurre-nav-text2" %}</span>
                    </div>
                    <div id="logout">
                        <li class="nav-item logout"><a href="{% url 'user_app:ulogout' %}">
                            <i class="fas fa-sign-out-alt fa-2x"></i></a>
                        </li>
                        <span class="text">{%  dis_play "purbeurre-nav-text3" %}</span>
                    </div>
                    {% endif %}
                    <div id="perso2">
                    <li class="nav-item perso2"><a href="{% url 'user_app:login' %}">
                        <img src="{%static 'img/perso2.png' %}" alt="mon compte"></a>
                    </li>
                    <p class="text">{%  dis_play "purbeurre-nav-text4" %}</p>
                    </div>
                    {% comment %}
                    <div id="language">
                        <li class="nav-item lang FR">
                            <a href="{% url 'index' %}"><img src="{% static 'img/FRmini.jpg' %}" alt="Francais"></a>
                        </li>
                    </div>
                    <div id="language">
                        <li class="nav-item lang UK">
                            <a href="{% url 'index' %}"><img src="{% static 'img/UKmini.jpg' %}" alt="English"></a>
                        </li>
                    </div>
                    {% endcomment %}
                    <div id="language">
                        <li class="nav-item lang FR">
                           <img src="{% static 'img/FRmini.jpg' %}" alt="Francais">
                        </li>
                    </div>
                    <div id="language">
                        <li class="nav-item lang UK">
                            <img src="{% static 'img/UKmini.jpg' %}" alt="English">
                        </li>
                    </div>
                </ul>



            </div>
        </div>
    </nav>

{% endblock navbar %}

templates/layouts/partials/_paginator.html
{% load dis_play %}
{% if page_obj.has_other_pages %}
    <div class="pagination row align-items-end justify-content-center text-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; {% dis_play "purbeurre-paginator-text1" %}</a>
                <a href="?page={{ page_obj.previous_page_number }}">{% dis_play "purbeurre-paginator-text2" %}</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">{% dis_play "purbeurre-paginator-text3" %}</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">{% dis_play "purbeurre-paginator-text4" %} &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %}

templates/layouts/partials/_scripts.html
{# the scripts part of the base template : Teh root index is the application home_app index --> 1 js file #}
{% load static %}
{% block scripts %}
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <!-- Jquery UI -->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'dist/js/scripts.js' %}"></script>
    {% static "" as baseUrl %}
    {% if not appname %}
        <script src="{{ baseUrl }}home_app/js/script.js"></script>
    {% else %}
        <script src="{{ baseUrl }}{{ appname }}/js/script.js"></script>
    {% endif %}

{% endblock scripts %}