home_app/urls.py
"""
    home_app URL Configuration

"""
from django.urls import path

from home_app import views as hav


app_name = 'home_app'
urlpatterns = [
    path('', hav.index, name='index'),
    path('index/', hav.index, name='index'),
    path('mentions/', hav.mentions, name='mentions'),
    path('test_error',hav.test_error, name='test_error'),
    path('set_language/', hav.set_language, name='set_language'),
]

products_app/urls.py
"""
    home_app URL Configuration

"""
from django.urls import path

from products_app import views as pav
from home_app import views as hav


app_name = 'products_app'
urlpatterns = [
    path('', hav.index, name='index'),
    path('search', pav.search_view, name='search'),
    path('search_substitute', pav.search_substitute_view, name='search_substitute'),
    path('detail', pav.ProductDetailView.as_view(), name='detail'),
    path('save_remove_bookmark/', pav.save_remove_bookmark, name='save_remove_bookmark'),
    path('list_bookmarks/', pav.BookmarkListView.as_view(), name='list_bookmarks'),
    path('initdb', pav.InitDBView.as_view(), name='initdb'),
]

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

from home_app import views as hav


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home_app/', include('home_app.urls')),
    path('user_app/', include('user_app.urls')),
    path('products_app/', include('products_app.urls')),
    path('', hav.index, name='index'),
    path('autocomplete_search/', hav.autocomplete_search, name='autocomplete_search'),
    path('accounts/login/', RedirectView.as_view(url='/user_app/login')),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_password_complete.html'),
         name='password_reset_complete'),

]

handler400 = 'home_app.errors.handler400'
handler403 = 'home_app.errors.handler403'
handler404 = 'home_app.errors.handler404'
handler500 = 'home_app.errors.handler500'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

user_app/urls.py
"""
    home_app URL Configuration

"""
from django.urls import path
from django.contrib.auth import views as auth_views


from user_app import views as uav
from home_app import views as hav


app_name = 'user_app'
urlpatterns = [
    path('', hav.index, name='index'),
    path('user_create', uav.user_create, name='user_create'),
    path('login', uav.user_login, name='login'),
    path('user_logout', uav.user_logout, name='ulogout'),
    path('change_password', uav.change_password, name='change_password'),
    # Reset password
    path('reset_password', uav.reset_psw, name='reset_password'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="registration/reset_password_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_password_complete.html'),
         name='password_reset_complete'),
]

products_app/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.utils.datastructures import MultiValueDictKeyError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import DetailView, TemplateView, ListView
from django.views.decorators.csrf import csrf_exempt
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
import json
from django.db.utils import IntegrityError
import threading


from products_app.tasks import init_db
from products_app.init import NB_ITEMS_PAGE
from products_app import substitutes as subst
from products_app.models import Product, Bookmark, ProductsWish


def search_view(request):
    """
        Display 1st resul of product search
        depends on search result :
        - Error --> just display the message
        - no product found --> ask to fetch data via openfoodfacts API en retry the search later
        - more than one product found --> display all the product to choose one and the go to the
            substitute page with this product
        - 1 product found --> just go to the substitute page with the found product
    """
    context = {'title': 'products_app-search-title'}
    if not request.user.is_authenticated:
        # user not authenticated --> not a 404 but a message !
        context['search_return'] = "4"
        return render(request, 'products_app/search.html', context=context)

    if request.method == 'POST':
        if 'chkcode' in request.POST:
            # product has been chosen in the list
            # put the barecode in session data
            # Get search_substitute
            request.session['code'] = request.POST['chkcode']
            return HttpResponseRedirect(reverse('products_app:search_substitute'))

        if 'yes' not in request.POST:
            # 1st passage
            try:
                context['item'] = request.POST['items_to_search']
            except MultiValueDictKeyError:
                context['item'] = request.POST['search_menu']
            # Search product --> return a queryset (None is an error)
            prod_to_search = Product.search_product(context['item'])
            request.session['item'] = context['item']
            if prod_to_search is None:
                # Error in search --> just display the message
                context['search_return'] = "0"
                return render(request, 'products_app/search.html', context=context)

            if len(prod_to_search) == 0:
                # Nothing found --> ask to fetch from OpenFoodFacts and then try again later
                context['search_return'] = "1"
                return render(request, 'products_app/search.html', context=context)
            elif len(prod_to_search) > 1:
                # More than one product found !!
                # paginator for the products
                page_obj = paginate(prod_to_search, 1)

                context['prods'] = page_obj
                context['search_return'] = "2"
                return render(request, 'products_app/search.html', context=context)
            else:
                # one product found redirect  search_substitute
                prod = prod_to_search.first()
                request.session['code'] = prod.code
                context['search_return'] = "3"
                return HttpResponseRedirect(reverse('products_app:search_substitute'))
        else:
            # no product found --> yes to search in openfoodfacts data
            item = request.session['item']
            try:
                ProductsWish.objects.create(pwname=item)
            except IntegrityError:
                pass
            task = threading.Thread(target=init_db, args=(False, ))
            task.start()
            return HttpResponseRedirect(reverse('home_app:index'))

    elif request.method == 'GET':
        # for the pagination  --> more than one product
        prod_to_search = Product.search_product(request.session['item'])
        # paginator
        page_number = int(request.GET.get('page', 1))
        page_obj = paginate(prod_to_search, page_number)

        context['search_return'] = "2"
        context['prods'] = page_obj
    return render(request, 'products_app/search.html', context=context)


def search_substitute_view(request):
    """
    function based view to select a substitute
    the product is in the request

    always with the get method
    Get the product through the barcode (more efficient than the name !)

    render the search_substitute.html template
    """
    context = {'title': 'products_app-search-subst-title', }
    if request.method == 'POST':
        pass
    else:
        prod_to_search = Product.objects.get(code=request.session['code'])
        context['chk'] = prod_to_search
        substitutes = subst.search_substitute(prod_to_search)
        # find the barcodes for all the selected product substitutes already bookmarked
        # put the in an array to get the green or red floppy !
        bookmarks = subst.search_bookmarks(prod_to_search.code, request.user.username)
        list_code_bookmarks = []
        for bookmark in bookmarks:
            list_code_bookmarks.append(bookmark.substitute.code)
            # The paginator
        if substitutes is not None:
            page_number = int(request.GET.get('page', 1))
            page_obj = paginate(substitutes, page_number)
            context['substitutes'] = page_obj
            context['list_bookmarks'] = list_code_bookmarks
    return render(request, "products_app/search_substitute.html", context=context)

@csrf_exempt
def save_remove_bookmark(request):
    """
    Remove or add a bookmark in database depends on data['action']
    called by Ajax but with POST (security reason). The decorator csrf_exempt is to avoid to generate_
    a csrf token in the javascript
    args : request
        the products (origin and bookmarks ) and the action (add or remove) are in the request in json format
    returns : OK or error in json format
    """
    if request.method == 'POST':
        request_data = json.loads(request.read().decode('utf-8'))
        user = request.user.username
        prod = str(request_data['subst'])
        subst = str(request_data['prod'])
        action = str(request_data['action'])
        try:
            if action == "remove":
                Bookmark.remove_bookmark(user, subst, prod)
            else:
                Bookmark.create_bookmark(user, subst, prod)
            data = {'data': 'OK'}
        except:
            data = {'data': 'ERREUR'}
    return JsonResponse(data)



class ProductDetailView(DetailView):
    """
    Detail of a product --> detail view
    The query is in get_object method

    """
    context_object_name = 'product'
    model = Product
    template_name = "products_app/detail_view.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_object(self):
        return Product.objects.get(code=self.code)
    """
    not used --> to be validated
    def get(self, request, *args, **kwargs):
        # print("get detail_view")
        self.code = request.session['code']
        self.object = self.get_object()
        context = self.get_context_data()
        return self.render_to_response(context=context)
    """
    def post(self, request, *args, **kwargs):
        self.code = request.POST['chkcode']
        self.object = self.get_object()
        context = self.get_context_data()
        context['nutrient_levels'] = self.object.get_nutrient_levels
        context['title'] = 'products_app-detail-view-title'
        return self.render_to_response(context=context)


@method_decorator(staff_member_required, name='get')
class InitDBView(TemplateView):
    """
    The initDB page
    - get method (to obtain the page)
        - Protected by the class decorator
    - post method if OK --> launch the InitDB
        - The initDB task is launch as a celery task "(delay) method)" : it runs in background
        - Return immediately to the homepage without waiting the end of InitDB
    """
    template_name = "products_app/initdb.html"
    context_object_name = 'init'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        context['title'] = 'products_app-initdb-title'
        return self.render_to_response(context=context)

    @method_decorator(staff_member_required())
    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        context['title'] = 'products_app-initdb-title'
        task = threading.Thread(target=init_db, args=(True, ))
        task.start()
        return HttpResponseRedirect(reverse('home_app:index'))


class BookmarkListView(ListView):
    """
    ListView for the bookmarks list
    Just a queryset defined and a context for the title
    """
    model = Bookmark
    template_name = "products_app/list_bookmarks.html"
    context_object_name = 'bookmarks'
    ordering = ['product']

    def get_queryset(self):
        queryset = self.model.objects.all().filter(buser=self.request.user).distinct('product')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'products_app-list-bookmarks-title'
        return context


def paginate(items, page_number):
    """
    paginator
    the NB_ITEMS_PAGE is defined in the setup.py
    args : items to paginate (queryset in example)
           page number --> in the page request --> send by the caller

    return the part of the items to be displayed (a part of a queryset in example :
        from 12 to 24 for the 2nd page)
    """
    paginator = Paginator(items, NB_ITEMS_PAGE)
    try:

products_app/templates/products_app/detail_view.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load define %}
{% load dis_play %}
{% block body_block %}
{% static "" as baseUrl %}
<div id="my_body">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center col-12 my_title">
                <section>
                <div>
                    <img type="image" class="img-thumbnail selected_prod" src="{{ product.photo_url }}" alt="image {{chk.pname}}" />
                </div>
                <div>
                    <h5><strong>{{ product.pname }}</strong> -
                        <img type="image" class="selected_prod"
                        src="{{ baseUrl }}{{ appname }}/img/Nutri-{{product.nutriscore_grade|upper}}.png"/>
                    </h5>
                </div>
                <div>
                    <h5>{% dis_play "products_app-detail-view-text1" %} <strong>{{ product.brand | title }}</strong> -
                        {% dis_play "products_app-detail-view-text2" %} {{ product.code }}
                    </h5>
                </div>
                </section>

        </div>        
        <hr />
        <div class="row col-12">
            <div class="col-sm-4 col12 ">
                <div class="col-12">
                    <h5 class="text-center"><strong>{% dis_play "products_app-detail-view-text3" %}</strong></h5>
                    <div class="row">
                    {% for k,v in nutrient_levels.items %}
                        <span class="col-1">
                            <img src="{{ baseUrl }}{{ appname }}/img/circle-{{v.0}}.png" />
                        </span>
                        <span class="col-10">{% dis_play k %} -  {% dis_play v.1 %}</span>
                    {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-sm-4 col-12">
                <h5 class="text-center"><strong>{% dis_play "products_app-detail-view-text4" %}</strong></h5>
                {% for cat in product.category.all %}
                <div clas="row col-12">
                    - {{cat}}
                </div>
                {% endfor %}
            </div>
            <div class="col-sm-4 col-12">
                <h5 class="text-center"><strong>{% dis_play "products_app-detail-view-text5" %}</strong></h5>
                {% for store in product.store.all %}
                <div clas="row col-12">
                    - {{store | title}}
                </div>
                {% endfor %}
            </div>    
        </div>
        {% if product.pbookmarks.all.count > 0 %}
        {# "define" and "plus" are templates tags created to define a var as integer  and add a value #}
        {# to a variable #}
            {% define 0 as bookmark_seen %}
                       
            {% for bookmark in product.pbookmarks.all %}
                {% if bookmark.buser|upper == user.get_username|upper %}
                    {% if bookmark_seen == 0 %}
                        {% plus bookmark_seen 1 as bookmark_seen %}
                        <hr />
                        <div class="row align-items-center justify-content-center text-center col-12">
                            <h5><strong>{% dis_play "products_app-detail-view-text6" %}</strong></h5>
                        </div>
                        <div class="row col-12">
                    {% endif %}
                    <div class="col-sm-2 col-6 ">
                        <form method="POST" action="{% url 'products_app:detail' %}" class="inline">
                            {% csrf_token %}
                            <div>
                                <input type="hidden" name="chkpname" value="{{bookmark.substitute.pname}}">
                                <input type="hidden" name="chkcode" value="{{bookmark.substitute.code}}">
                                <input type="image" class="img-thumbnail" src="{{ bookmark.substitute.photo_url }}" 
                                alt="image {{bookmark.product.pname}}" />
                            </div>
                        </form>
                    </div>
                    <div class="col-10">
                        {{ bookmark.substitute.pname }} - <img type="image" class="selected_prod"  
                            src="{{ baseUrl }}{{ appname }}/img/Nutri-{{product.nutriscore_grade|upper}}.png"/>
                    </div>
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <hr />
        <div class='row  justify-content-center col-12'>
            <span>{% autoescape off %}{% dis_play "products_app-detail-view-text7" %} {% endautoescape %}
                <a href="{{product.product_url}}" target="_blank"> {% dis_play "products_app-detail-view-text8" %}</a></span>

        </div>
        {% include 'layouts/partials/_back.html' %}
    </div>
</div>
{% endblock %}

products_app/templates/products_app/initdb.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load dis_play %}
{% block body_block %}
<header class="my_body">
    <div class="container">
        <div class="alert alert-danger" role="alert">
            <p>{% autoescape off %}{% dis_play "products_app-initdb-text1"%}{% endautoescape %}</p>
            <p>{% dis_play "products_app-initdb-text2"%}</p>
        </div>
        <h5>{% dis_play "products_app-initdb-text3"%}</h5>
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="{% dis_play "products_app-initdb-button1"%}" class="btn btn-danger">
        </form>
        <hr />
        <div class="row justify-content-center">
            <a href="{% url 'home_app:index' %}"><input type="button" class="btn btn-primary"
                                                        value="{% dis_play "products_app-initdb-button2"%}" /></a>
        </div>
    </div>
</header>
{% endblock %}

products_app/templates/products_app/list_bookmarks.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load define %}
{% load dis_play %}
{% static "" as baseUrl %}
{% block body_block%}
<div id="my_body">
    <div class="container">
        <header class="row align-items-center justify-content-center text-center col-12 my_title2">
            <h5>{%  dis_play "products_app-list-bookmarks-text1" %} {{user.get_username|upper}} - {{user.email}}</h5>
        </header>
    </div>
    <div class="container">
        {% if bookmarks %}
        <div class="row"> 
            <div class="col-12">   
                <div class="row">
                    <div class="col-6 text-center border border-dark">
                        {%  dis_play "products_app-list-bookmarks-text2" %}
                    </div>
                    <div class="col-6 text-center border border-dark">
                        {%  dis_play "products_app-list-bookmarks-text3" %}
                    </div>
                </div>     
            </div>
        </div>   
        <div class="row">
            <div class='col-12 border border-dark'>                
                {% for bookmark in bookmarks %}
                    <div class="row align-items-center  border-bottom border-dark">
                        <div class="col-6 text-center mycol border-right border-dark">
                            <form method="POST" action="{% url 'products_app:detail' %}" >
                                {% csrf_token %}
                                <input type="hidden" name="chkpname" value="{{bookmark.product.pname}}">
                                <input type="hidden" name="chkcode" value="{{bookmark.product.code}}">
                                <input type="image" class="img-thumbnail" src="{{ bookmark.product.photo_url }}" 
                                alt="image {{bookmark.product.pname}}" /><br />
                                {{ bookmark.product }}
                            </form>
                        </div>
                        <div class="col-6 mycol border-left border-dark">
                        {% for subst in bookmark.product.pbookmarks.all %}
                            {% if subst.buser|upper == user.get_username|upper %}
                                <div class="mycol text-center mb1">
                                    <form method="POST" action="{% url 'products_app:detail' %}" >
                                        {% csrf_token %}
                                        <input type="hidden" name="chkpname" value="{{subst.substitute.pname}}">
                                        <input type="hidden" name="chkcode" value="{{subst.substitute.code}}">                            
                                        <input type="image" class="img-thumbnail" src="{{ subst.substitute.photo_url }}" 
                                        alt="image {{subst.substitute.pname}}" /><br />                                                       
                                        {{ subst.substitute}}
                                        
                                    </form>
                                </div>
                            {% endif %}
                        {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% else %}
            <div class="col-md-4 col-12 ligne justify-content-center text-center">
                <h5>{%  dis_play "products_app-list-bookmarks-text4" %}</h5>
            </div>
        {% endif %}
        {% include 'layouts/partials/_back.html' %}
    </div>
</div>
{% endblock %}

products_app/templates/products_app/search.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load dis_play %}
{% block body_block %}
<header class="my_body">
    <div class="container">
        {% if item %}
        <div class="row align-items-center justify-content-center text-center col-12 my_title">
            <h2 class="my_title">{% dis_play "products_app-search-text1" %} {{ item }}</h2>
        </div>
        {% endif %}
        {% if search_return == "0" %}
        {# Undefined error during the search #}
        <div class="row align-items-center justify-content-center text-center col-12 my_title">
            <h2>{% dis_play "products_app-search-text2" %}</h2>
            <div class="row align-items-center justify-content-center text-center col-12">
                <a href="{% url 'home_app:index' %}" class="btn btn-secondary " name="no">
                    {% dis_play "products_app-search-button1" %}</a>
            </div>
        </div>
        {% elif search_return == "4" %}
        {# Unauthenticated user is not authorized --> the 404 is not clear enough #}
            <div class="row align-items-center justify-content-center text-center col-12 my_title">
                <h2>{% dis_play "products_app-search-text3" %}</h2>
                <h5>{% dis_play "products_app-search-text4" %}</h5>
                <h5>{% dis_play "products_app-search-text5" %}</h5>
            </div>
            <div class="row align-items-center justify-content-center text-center col-12">
                <div class="col-6 ">
                    <a href="{% url 'user_app:login' %}" class="btn btn-primary " name="yes">
                        {% dis_play "products_app-search-button2" %}</a>
                </div>
                <div class="col-6">
                    <a href="{% url 'home_app:index' %}" class="btn btn-secondary " name="no">
                        {% dis_play "products_app-search-button1" %}</a>
                </div>
            </div>
        {% elif search_return == "1" %}
        {# no product found #}
            <div class="row align-items-center justify-content-center text-center col-12 my_title">
                <p><h3>{% dis_play "products_app-search-text6" %}</h3>
                <h5>{% dis_play "products_app-search-text7" %}</h5>
                <h5>{% dis_play "products_app-search-text8" %}</h5></p>
                <h5>{% dis_play "products_app-search-text9" %}</h5>
            </div>
            <div class="row align-items-center justify-content-center text-center col-12">
                <div class="col-6 ">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary btn_yes" name="yes" value=
                                {% dis_play "products_app-search-button3" %}>
                    </form>
                </div>
                <div class="col-6">
                    <a href="{% url 'home_app:index' %}" class="btn btn-secondary btn_no" name="no">
                        {% dis_play "products_app-search-button1" %}</a></a>
                </div>
            </div>
        {% elif search_return == "2" %}
        {# several products found ! Choose one ! #}
        <div class="row align-items-center justify-content-center text-center col-12 my_title">
            <h3>{% dis_play "products_app-search-text10" %}</h3>
            <h5>{% dis_play "products_app-search-text11" %}</h5>
        </div>
        <section class="col-12">
            <div class="row equal align-items-end">
                {% for prod in prods %}
                    <div class="col-md-4 col-12 ligne justify-content-center text-center  ">
                        <form method="POST" action="{% url 'products_app:search' %}" class="inline">
                            {% csrf_token %}
                            <div>
                                <input type="hidden" name="chkpname" value="{{prod.pname}}">
                                <input type="hidden" name="chkcode" value="{{prod.code}}">
                                <input type="image" class="img-thumbnail" src="{{ prod.photo_url }}" 
                                    alt="image {{chk.pname}}"/>
                            </div>
                            <span>{{ prod.pname }} </span>
                        </form>
                    </div>
                {% endfor %}
            </div>
            {% include 'layouts/partials/_paginator.html' with page_obj=prods %}
        </section>
        {% endif %}
        {% include 'layouts/partials/_back.html' %}
    </div>
</header>
{% endblock body_block %}

products_app/templates/products_app/search_substitute.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load dis_play %}
{% block body_block %}
{% static "" as baseUrl %}
<div id="my_body">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center col-12 my_title2">
            <form method="POST" action="{% url 'products_app:detail' %}" class="inline">
                {% csrf_token %}
                <div>
                    <input type="hidden" name="chkpname" value="{{chk.pname}}">
                    <input type="hidden" name="chkcode" value="{{chk.code}}">
                    <input type="image" class="img-thumbnail selected_prod" src="{{ chk.photo_url }}" alt="image {{chk.pname}}" />
                </div>
                <h5>{{ chk.pname }} - <img type="image" class="selected_prod"  src="{{ baseUrl }}{{ appname }}/img/Nutri-{{chk.nutriscore_grade|upper}}.png"/>
                </h5>
            </form>
        </div>
        <hr />
        <!--
        {{chk.pname}} - {{chk.code}}  {% for cat in chk.category.all %} {{ cat }} - {% endfor %}
        -->
        <br />
        <section class="col-12">
            <div class="row equal align-items-end">
                {% if substitutes %}
                {% for subst in substitutes %}
                    <div class="col-md-4 col-12 ligne justify-content-center text-center">
                        <form method="POST" action="{% url 'products_app:detail' %}" class="inline">
                            {% csrf_token %}
                            <div>
                                <input type="hidden" name="chkpname" value="{{subst.pname}}">
                                <input type="hidden" name="chkcode" value="{{subst.code}}">
                                <input type="image" class="img-thumbnail" src="{{ subst.photo_url }}" 
                                    alt="image {{subst.pname}}"/>
                            </div>
                                <div id="floppy_save">
                                {% if subst.code in list_bookmarks %}
                                    <i id="{{subst.code}}-{{chk.code}}"  class="fa fa-save floppy-red" aria-hidden="true"></i> 
                                {% else %}
                                    <i id="{{subst.code}}-{{chk.code}}"  class="fa fa-save floppy-green" aria-hidden="true"></i>
                                {% endif %}
                                <span class="text_floopy"> - </span><!-- </a> -->
                                <span>{{ subst.pname | truncatechars:20 }} - <img type="image" class="selected_prod"  src="{{ baseUrl }}{{ appname }}/img/Nutri-{{subst.nutriscore_grade|upper}}.png"/>
                                </span>
                                </div>
                        </form>
                    </div>
                {% endfor %}
            </div>
            {% include 'layouts/partials/_paginator.html' with page_obj=substitutes %}
            {% else %}
                <div class="col-md-4 col-12 ligne justify-content-center text-center">
                    <h5>{% dis_play "user_app-search-subst-text1" %}</h5>
                </div>
            {%endif%}
        </section>
        {% include 'layouts/partials/_back.html' %}
    </div>
</div>
{% endblock body_block %}